Feature/ansonlee99/1011099544 sidebar UI
TritonSE/Supply-Chain pull request #12
Opened 2021-02-14 05:46 UTC by AnsonLee99

### Administrative Info
Monday Board ID: 1011099544
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[Monday Item ID]-[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
Added sidebar to the website. Items can be expanded individually or by clicking on "expand-all". Items can also be sorted either alphabetically or by expiration date. 

One thing to note: when sorting by expiration date, the plus sign on the item header seems a bit out-of-place since the item cannot be expanded. However, I kept the plus sign there since that's what is shown on the Figma design. I also removed the "expand-all" button since it served no purpose when sorting by expiration date.

Disclaimer: This PR also includes some changes to add_button.js since I moved that file to its own directory. 

### Testing
Clicked around on the headers to verify they expanded/collapsed correctly. Changed the "sort-by" dropdown to check values are being correctly sorted.

### Confirmation of Change 
Sort-by: Alphabetical
![image](https://user-images.githubusercontent.com/36427506/107869464-46864180-6e43-11eb-88a9-a1f7c48cc404.png)
----------------------
Sort-by: Expiry
![image](https://user-images.githubusercontent.com/36427506/107869493-99f88f80-6e43-11eb-9d8e-5f4565d2fce8.png)

2021-02-14 06:25 UTC, petabite approved these changes
Nicee! Works perfectly. Yeah, good point, we should probably bring up the plus icon being there when sorting by expiration to the design team since that is a little confusing.

2021-02-14 06:25 UTC, petabite commented on client/src/home/sidebar/Sidebar.js
> +    if (diff != 0) {
should this be a `!==` ?
```suggestion
    if (diff !== 0) {
```

2021-02-14 07:44 UTC, hahsu requested changes
Nice work! Sidebar.js and SidebarItem.js are both pretty lengthy files. Can you add inline comments to better describe what each chunk of code is doing?

2021-02-14 23:31 UTC, AnsonLee99 commented
> Nice work! Sidebar.js and SidebarItem.js are both pretty lengthy files. Can you add inline comments to better describe what each chunk of code is doing?

Done!

2021-02-15 07:51 UTC, hahsu approved these changes
lgtm!

2021-02-15 08:08 UTC, merged