Refactor/justinyaodu/1058459663 add batchid
TritonSE/Supply-Chain pull request #14
Opened 2021-02-17 01:41 UTC by justinyaodu

### Administrative Info
Monday Board ID: 1058459663
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[Monday Item ID]-[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
What changes did you make?
- Added the `batchId` field to the Mongoose schema, and modified the indexing to enforce that the batch IDs are unique.

### Testing
How did you confirm your changes worked? 
- We think the code looks good, but we can't test it without changing the routes, which is going to be done separately. If there are issues we can fix them then.

### Confirmation of Change 
Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.
- N/A

2021-02-17 02:37 UTC, hahsu requested changes

2021-02-17 02:37 UTC, hahsu commented on client/src/MongodbFunctions.js
> -        itemId: itemId,
won't we need batchId here?

2021-02-17 02:37 UTC, hahsu commented on client/src/MongodbFunctions.js
>   * @param {string} outDate The date that this batch should be sent by.
can we update the comments, line 6 still has itemID

2021-02-17 02:37 UTC, hahsu commented on backend/routes/items.js
> -  const { itemName, itemId, weight } = req.body;
won't we need batchId here?

2021-02-17 07:38 UTC, hahsu approved these changes
lgtm, thank you!

2021-02-19 02:11 UTC, petabite approved these changes
Looks good!

2021-02-19 03:56 UTC, merged