Feature/benson272/983739318 item routes
TritonSE/Supply-Chain pull request #6
Opened 2021-01-21 02:00 UTC by Benson272

### Administrative Info
Monday Board ID: 853628905
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[Monday Item ID]-[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
What changes did you make?
- created routes for adding items and getting all items (localhost:9000/items/addItem and localhost:9000/items/getAllItems)

### Testing
How did you confirm your changes worked? 
- Sending POST and GET requests to add and get items from db
- Tested by adding items on same date (if added on same date, items should be combined into one batch)
- Tested by adding an item that does not already exist

### Confirmation of Change 
Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.

| Screenshot of database after inserting items |
![image](https://user-images.githubusercontent.com/55808666/105269564-059f5380-5b49-11eb-9af0-d8e70308d462.png)

| Screenshot of api route |
![image](https://user-images.githubusercontent.com/55808666/105269690-4ac38580-5b49-11eb-93de-c96577b587b8.png)

| Screenshot of result from getAllItems route |
![image](https://user-images.githubusercontent.com/55808666/105269717-58790b00-5b49-11eb-87cb-da973fd323f4.png)

2021-01-21 02:15 UTC, justinyaodu requested changes
I left a comment on one thing that might be a typo, and added `===` instead of `==` for a null check, but it looks ready to merge otherwise. Good stuff!

2021-01-21 02:15 UTC, justinyaodu commented on backend/routes/index.js
> +  res.send("Sup.ply Chain");
Is "Sup.ply" a typo?

2021-01-21 02:23 UTC, hahsu requested changes

2021-01-21 02:23 UTC, hahsu commented on backend/routes/items.js
> +      for (let batch of item.batches) {
Is this necessary? I thought we had talked about being able to use a property value to search through the array of batches. Maybe $elemMatch? [https://docs.mongodb.com/manual/reference/operator/query/elemMatch/](url)

2021-01-21 02:23 UTC, hahsu commented on backend/routes/items.js
> +  const today = toUTCMidnight(new Date());
Is this getting today's date? Don't we want the expiration date here, which will be passed to you from the form? I guess depending on what design team answers regarding how the frontend calendar looks, we might need to keep track of what day the batch was added AND the expiration date. So maybe our batch needs the fields startDate and expirationDate. Can you update the model, and reflect that change in this file as well?

2021-01-21 02:52 UTC, petabite commented on backend/routes/index.js
> +  res.send("Sup.ply Chain");
Oops yup. Nice catch!

2021-01-22 02:44 UTC, hahsu approved these changes
lgtm

2021-01-22 02:53 UTC, justinyaodu approved these changes
LGTM!

2021-01-22 02:55 UTC, merged